import { PRONG_HEIGHT, PRONG_WIDTH, TILE_SIZE } from '@mander/model';

export const FALLING_SPIKE_TRIGGER_TILES = 2;

export const FALLING_SPIKE_TRIGGER_RANGE =
  FALLING_SPIKE_TRIGGER_TILES * TILE_SIZE;

export const FALLING_SPIKE_WIDTH = PRONG_WIDTH;
export const FALLING_SPIKE_HEIGHT = PRONG_HEIGHT;

export const FALLING_SPIKE_INSET_X = (TILE_SIZE - FALLING_SPIKE_WIDTH) / 2;

export const FALLING_SPIKE_PIT_TILES = 2;
